# Generated by Django 2.2.1 on 2019-09-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('categories', models.CharField(choices=[('WB', 'Web App'), ('AD', 'Android'), ('Dsk', 'Desktop App')], max_length=1)),
                ('status', models.CharField(choices=[('RA', 'Recently added'), ('MW', 'Most Watched'), ('TR', 'Top Rated')], max_length=200)),
                ('year_production', models.DateField()),
                ('View_counts', models.IntegerField(default=0)),
            ],
        ),
    ]
