# Generated by Django 2.2.1 on 2019-09-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='categories',
            field=models.CharField(choices=[('WB', 'Web App'), ('AD', 'Android'), ('Dsk', 'Desktop App')], max_length=20),
        ),
    ]
