# Generated by Django 2.2.1 on 2019-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20190913_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
