# Generated by Django 2.2.1 on 2019-09-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20190913_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='cast',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CodeLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('D', 'Download_link'), ('W', 'Watch_link')], max_length=600)),
                ('link', models.URLField()),
                ('cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_watch_link', to='hub.hub')),
            ],
        ),
    ]
