# Generated by Django 2.2.1 on 2019-09-17 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20190917_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelinks',
            name='cod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.hub'),
        ),
    ]
