# Generated by Django 2.2.1 on 2019-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20190917_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='categories',
            field=models.CharField(choices=[('web app', 'Web App'), ('android', 'Android'), ('desktop app', 'Desktop App')], max_length=20),
        ),
    ]
