# Generated by Django 2.2.1 on 2019-09-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20190918_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hub',
            old_name='categories',
            new_name='category',
        ),
    ]
