# Generated by Django 2.2.1 on 2019-09-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20190920_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='category',
            field=models.CharField(choices=[('W', 'Web App'), ('A', 'Android'), ('D', 'Desktop App')], max_length=20),
        ),
    ]
